apiVersion: v1
kind: Service
metadata:
  name: atomix-memory-node
  namespace: micro-onos
spec:
  type: ClusterIP
  selector:
    app: atomix-memory-node
  ports:
    - name: grpc
      port: 5678
      targetPort: 5678
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: atomix-memory-node
  namespace: micro-onos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: atomix-memory-node
  template:
    metadata:
      labels:
        app: atomix-memory-node
    spec:
      containers:
        - name: memory-node
          image: docker.io/atomix/memory-storage-node:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5678
