apiVersion: v1
kind: ServiceAccount
metadata:
  name: atomix-controller
  namespace: micro-onos
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: atomix-controller-role
rules:
  - apiGroups: ["", "apps", "atomix.io"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: atomix-controller-binding
subjects:
  - kind: ServiceAccount
    name: atomix-controller
    namespace: micro-onos
roleRef:
  kind: ClusterRole
  name: atomix-controller-role
  apiGroup: rbac.authorization.k8s.io
