apiVersion: apps/v1
kind: Deployment
metadata:
  name: atomix-pod-memory-controller
  namespace: micro-onos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: atomix-pod-memory-controller
  template:
    metadata:
      labels:
        app: atomix-pod-memory-controller
    spec:
      containers:
        - name: controller
          image: docker.io/atomix/pod-memory-controller:latest
          imagePullPolicy: IfNotPresent
          args:
            - "--namespace=micro-onos"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: atomix-memory-store-config
  namespace: micro-onos
data:
  config.json: |
    {
      "stores": [
        {
          "id": "local-memory",
          "type": "memory"
        }
      ]
    }
