apiVersion: apps/v1
kind: Deployment
metadata:
  name: onos-config
  namespace: micro-onos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: onos-config
  template:
    metadata:
      labels:
        app: onos-config
    spec:
      containers:
        - name: onos-config
          image: onosproject/onos-config:latest
          args:
            - "--topoEndpoint=onos-topo:5150"
            - "--allowUnvalidatedConfig"
            - "--storeType=memory"
          ports:
            - containerPort: 5150
