apiVersion: v1
kind: ConfigMap
metadata:
  name: atomix-sidecar-config
  namespace: micro-onos
data:
  config.json: |
    {
      "runtime": {
        "routes": [
          {
            "store": {
              "name": "local-store"
            }
          }
        ]
      },
      "stores": [
        {
          "name": "local-store",
          "driver": {
            "name": "memory"
          }
        }
      ]
    }
---
apiVersion: v1
kind: Service
metadata:
  name: onos-topo
  namespace: micro-onos
spec:
  type: ClusterIP
  selector:
    app: onos-topo
  ports:
    - name: grpc
      port: 5150
      targetPort: 5150
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: onos-topo
  namespace: micro-onos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: onos-topo
  template:
    metadata:
      labels:
        app: onos-topo
    spec:
      containers:
        - name: onos-topo
          image: onosproject/onos-topo:latest
          args:
            - "--bind-port=5150"
          ports:
            - containerPort: 5150
        - name: atomix-sidecar
          image: docker.io/atomix/sidecar:latest
          imagePullPolicy: IfNotPresent
          args:
            - "--config=/etc/atomix/config.json"
          ports:
            - containerPort: 5678
            - containerPort: 5679
          volumeMounts:
            - name: atomix-config
              mountPath: /etc/atomix
      volumes:
        - name: atomix-config
          configMap:
            name: atomix-sidecar-config
---
apiVersion: v1
kind: Service
metadata:
  name: onos-config
  namespace: micro-onos
spec:
  type: ClusterIP
  selector:
    app: onos-config
  ports:
    - name: gnmi
      port: 5150
      targetPort: 5150
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: onos-config
  namespace: micro-onos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: onos-config
  template:
    metadata:
      labels:
        app: onos-config
    spec:
      containers:
        - name: onos-config
          image: onosproject/onos-config:latest
          args:
            - "--topoEndpoint=onos-topo:5150"
            - "--allowUnvalidatedConfig"
          ports:
            - containerPort: 5150
        - name: atomix-sidecar
          image: docker.io/atomix/sidecar:latest
          imagePullPolicy: IfNotPresent
          args:
            - "--config=/etc/atomix/config.json"
          ports:
            - containerPort: 5678
            - containerPort: 5679
          volumeMounts:
            - name: atomix-config
              mountPath: /etc/atomix
      volumes:
        - name: atomix-config
          configMap:
            name: atomix-sidecar-config
