id: "devicesim-1"
kind_id: "devicesim"
display_name: "In-Cluster Quantum Simulator"
address: "localhost:10161"
kind: "devicesim"
version: "1.0.x"
role: "simulator"

protocols:
  - name: "gnmi"
    port: 10161

aspects:
  onos.topo.Configurable:
    address: "localhost:10161"
    type: "devicesim"
    version: "1.0.x"

  onos.topo.TLSOptions:
    plain: true
    insecure: true
