id: "devicesim-1"
kind_id: "devicesim"
display_name: "In-Cluster Quantum Simulator"
address: "devicesim-1.micro-onos.svc.cluster.local:10161"
kind: "devicesim"
version: "1.0.x"
role: "simulator"
protocols:
  - name: "gnmi"
    port: 10161
aspects:
  onos.topo.Configurable:
    address: "devicesim-1.micro-onos.svc.cluster.local:10161"
    type: "devicesim"
    version: "1.0.x"
  onos.topo.TLSOptions:
    insecure: true
    plain: true
