id: "devicesim-1"
kind_id: "controller-quantum-switching"
display_name: "In-Cluster Quantum Simulator"
address: "device-simulator:11161"
kind: "controller-quantum-switching"
version: "1.0.0"
role: "simulator"

protocols:
  - name: "gnmi"
    port: 11161

aspects:
  onos.topo.Configurable:
    address: "device-simulator:11161"
    type: "controller-quantum-switching"
    version: "1.0.0"

  onos.topo.TLSOptions:
    plain: true
    insecure: true
