id: "quantum-node-1"
kind_id: "devicesim"
display_name: "Physical BeagleBone Quantum Switch 1"
address: "10.0.0.254:50051"
kind: "devicesim"
version: "1.0.x"
role: "quantum-switch"
protocols:
  - name: "gnmi"
    port: 50051
  - name: "gnoi"
    port: 50052
  - name: "netconf"
    port: 8300
aspects:
  onos.topo.Configurable:
    address: "10.0.0.254:50051"
    type: "devicesim"
    version: "1.0.x"
  onos.topo.TLSOptions:
    insecure: true
    plain: true
