id: "quantum-node-1"
kind_id: "controller-quantum-switching"
display_name: "Physical BeagleBone Quantum Switch 1"
address: "10.0.0.254:50051"
kind: "controller-quantum-switching"
version: "1.0.0"
role: "quantum-switch"

protocols:
  - name: "gnmi"
    port: 50051
  - name: "gnoi"
    port: 50051
  - name: "netconf"
    port: 8300

aspects:
  onos.topo.Configurable:
    address: "10.0.0.254:50051"
    type: "controller-quantum-switching"
    version: "1.0.0"

  onos.topo.TLSOptions:
    plain: true
    insecure: true
