id: "quantum-node-1"
display_name: "Physical BeagleBone Quantum Switch 1"
address: "10.0.0.254:9339"
kind: "beaglebone-qswitch"
role: "quantum-switch"
protocols:
  - name: "gnmi"
    port: 9339
  - name: "gnoi"
    port: 9339
  - name: "netconf"
    port: 830
