# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: quantum_switch.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'quantum_switch.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14quantum_switch.proto\x12\x11quantum.switch.v1\"$\n\x13\x43rossConnectRequest\x12\r\n\x05state\x18\x01 \x01(\x08\"8\n\x14\x43rossConnectResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x0f\n\rStatusRequest\";\n\x0eStatusResponse\x12\x14\n\x0cis_connected\x18\x01 \x01(\x08\x12\x13\n\x0bswitch_type\x18\x02 \x01(\t2\xd8\x01\n\x14QuantumSwitchService\x12\x62\n\x0fSetCrossConnect\x12&.quantum.switch.v1.CrossConnectRequest\x1a\'.quantum.switch.v1.CrossConnectResponse\x12\\\n\x15GetCrossConnectStatus\x12 .quantum.switch.v1.StatusRequest\x1a!.quantum.switch.v1.StatusResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'quantum_switch_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CROSSCONNECTREQUEST']._serialized_start=43
  _globals['_CROSSCONNECTREQUEST']._serialized_end=79
  _globals['_CROSSCONNECTRESPONSE']._serialized_start=81
  _globals['_CROSSCONNECTRESPONSE']._serialized_end=137
  _globals['_STATUSREQUEST']._serialized_start=139
  _globals['_STATUSREQUEST']._serialized_end=154
  _globals['_STATUSRESPONSE']._serialized_start=156
  _globals['_STATUSRESPONSE']._serialized_end=215
  _globals['_QUANTUMSWITCHSERVICE']._serialized_start=218
  _globals['_QUANTUMSWITCHSERVICE']._serialized_end=434
# @@protoc_insertion_point(module_scope)
